# generated by fastapi-codegen:
#   filename:  amap.json
#   timestamp: 2025-06-17T09:08:09+00:00

# Minimal template test
from fastapi import FastAPI, Request
from req_api import handel_api

app = FastAPI(title='Minimal Test App', version='0.0.1')


# A single endpoint to see if anything gets generated
@app.get("/")
def read_root(request: Request) -> dict:  # Added request and return type
    return handel_api(request)


# End of minimal template test
